// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('tjmanzouApp').controller('MainCtrl', [
    '$scope', function($scope) {
      return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    }
  ]);

}).call(this);
